# Generated by Django 4.1.6 on 2023-04-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
                ("protein", models.IntegerField()),
                ("fat", models.IntegerField()),
                ("carbs", models.IntegerField()),
                ("calories", models.IntegerField()),
            ],
            options={"verbose_name_plural": "ingredients",},
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ingredients", models.CharField(max_length=600)),
                ("proteinLevel", models.CharField(max_length=255)),
                ("fatLevel", models.CharField(max_length=255)),
            ],
            options={"verbose_name_plural": "recipies",},
        ),
        migrations.CreateModel(
            name="Restriction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ingredientId", models.IntegerField()),
                ("userName", models.CharField(max_length=255)),
            ],
            options={"verbose_name_plural": "Restrictions",},
        ),
        migrations.CreateModel(
            name="RestrictionPreset",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={"verbose_name_plural": "RestrictionPresets",},
        ),
        migrations.CreateModel(
            name="RestrictionPresetIngredient",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("presetid", models.IntegerField()),
                ("ingredientId", models.IntegerField()),
            ],
            options={"verbose_name_plural": "RestrictionPresetIngredients",},
        ),
        migrations.CreateModel(
            name="SelectedRestrictionPreset",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("presetid", models.IntegerField()),
                ("userName", models.CharField(max_length=255)),
            ],
            options={"verbose_name_plural": "SelectedRestrictionPresets",},
        ),
    ]
