# Generated by Django 4.1.6 on 2023-04-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipegenerator",
            "0002_restrictionpreset_restrictionpresetingredient_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="restriction",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
