# Generated by Django 4.1.6 on 2023-04-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipegenerator", "0003_alter_restriction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="restriction",
            name="id",
            field=models.CharField(
                default="B907F", max_length=50, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="restrictionpreset",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
