# Generated by Django 4.1.6 on 2023-02-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ingredients", models.CharField(max_length=255)),
                ("proteinLevel", models.CharField(max_length=255)),
                ("fatLevel", models.CharField(max_length=255)),
            ],
            options={"verbose_name_plural": "recipies",},
        ),
    ]
